### ISSUE TITLE
hardcoded content id to hmrc contact finder

### ISSUE THREAD

**Issue by mcgoooo** [alphagov/contacts-admin#263]
Hi,

a couple of questions really, i may be shooting into the air here, but i thought i would record my questions.

We have a [hardcoded finder content-id](https://github.com/alphagov/contacts-admin/blame/master/app/services/publish_finders.rb#L22) which is a bit fishy for me for two reasons

1. mixing content and config, it took me a fair while to figure out how it was getting the finder
2. hardcoding id's across environments is a bit weird, and will cause it to break subtly maybe?

**Comment by tijmenb** [comment]
A bunch of publishing applications publish one-of-a-kind pages like this finder. They have the content hard coded. Some other examples:

- https://github.com/alphagov/whitehall/tree/master/lib/finders 
- https://github.com/alphagov/collections-publisher/blob/master/app/presenters/root_browse_page_presenter.rb.

I'm not sure what the alternative would be for these pages.

`content_ids` are always consistent across environments, since we copy prod -> staging -> integration.

**Comment by mcgoooo** [comment]
ok, cool, i thought there would be some form of api to look these thigns up dynamically, i'll close this as it was mainly just a question.
